### ISSUE TITLE
Model not running 

### ISSUE THREAD

**Issue by katagaur** [nevinbaiju/diabetic-retinopathy#3]
OSError: SavedModel file does not exist at: /home/nevin/Nevin/projects/diabetic-retinopathy/website/eye/model.hd5/{saved_model.pbtxt|saved_model.pb}

**Comment by katagaur** [comment]
It gives the above error when running the python3 manage.py runserver

**Comment by nevinbaiju** [comment]
This project was developed when I was just starting in learning. So there will be a problem of absolute paths here and there. Meaning, the paths will only work on my system. You can either change that to your absolute path for a quick fix or run the project from the root directory of the project and specify a relative path there instead. Please feel free to raise a pull request if you are successfully converting the absolute paths to relative paths.
